### ISSUE TITLE
Command-line client install issue

### ISSUE THREAD

**Issue by cristi8** [bauerj/mac_vendor_lookup#1]
The command-line version doesn't work by default because of a missconfiguration in setup.py

setup.py mentions:
`
entry_points={  # Optional
        'console_scripts': [
            'mac_vendor_lookup=lookup:main',
        ],
    },
`

I believe instead of lookup:main it should be mac_vendor_lookup:main

PS: Thanks for the nice tool!

**Comment by bauerj** [comment]
Thank you, that did fix the issue!
