### ISSUE TITLE
Error while analyze mac

### ISSUE THREAD

**Issue by usbport11** [bauerj/mac_vendor_lookup#12]
Good day!

Code:
```
vendor = MacLookup().lookup("B0:7B:25:C1:64:34")
print(vendor)
```

Result:
```
Traceback (most recent call last):
  File "./test-paramiko.py", line 56, in <module>
    vendor = MacLookup().lookup("B0:7B:25:C1:64:34")
  File "/usr/local/lib/python3.6/site-packages/mac_vendor_lookup.py", line 110, in lookup
    return self.loop.run_until_complete(self.async_lookup.lookup(mac))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/mac_vendor_lookup.py", line 94, in lookup
    return self.prefixes[mac[:6]].decode("utf8")
KeyError: b'B07B25'
```

How fix this?

**Comment by bauerj** [comment]
Hi,

please try 

```
MacLookup().update_vendors()
```

and see if that fixes the issue. The included vendor list might be too old, I guess I should publish a new build.

**Comment by usbport11** [comment]
Can i dowload file http://standards-oui.ieee.org/oui.txt manually and replace in system /usr/local/cache/mac-vendors.txt?

**Comment by bauerj** [comment]
No. Do you see an error when updating?

**Comment by usbport11** [comment]
Update file. Problem with this MAC dissapear.
Appear next issuse with mac that can't be resolved - added try catch.

```
for val in mass:
	values = val.split(' ')
		try:
			vendor = MacLookup().lookup(values[2])
		except:
			vendor = "Not found"
		print("%s %s %s %s %s" % (values[0], values[1], values[2], values[3], vendor))
```

Thank you.

**Comment by bauerj** [comment]
I'm glad it works now! I'll leave this issue open until I release an update with a newer OUI list.

**Comment by bauerj** [comment]
I've released a newer build with current OUIs now.

**Comment by Eldoprano** [comment]
I was getting the same error and also figured out that it was because the MAC wasn't in the OUI list. But in my case I'm using this library to check if a MAC is valid or not (Which causes a lot of misses).
I know that I can build a try-catch in my code, but it may be a good idea for this package to detect when a MAC wasn't found, and return something like a blank string.

**Comment by bauerj** [comment]
If you just want to check if the format is valid, you can check for `InvalidMacError` and ignore the `KeyError`:

```python
mac = MacLookup()

try:
    mac.lookup("B0:7B:25:C1:64:34xyz")
except InvalidMacError as e:
    print("Invalid", e)
except:
    pass
```

**Comment by Eldoprano** [comment]
Oh, with invalid MAC address I meant MAC Adresses which OUI isn't registered in the IEEE list. Something like this:
`dc:eb:a3:07:c2:f1`
Those MAC Addresses are sometimes found in Probe Requests generated by smartphones that randomize their whole MAC, even the Local Bit.

**Comment by bauerj** [comment]
Oh, I get it. You want a more helpful exception. Yes, that's definitely something that I can implement.

**Comment by Eldoprano** [comment]
Thanks ^^ And thanks for this library. It's helping me a lot with my research

**Comment by bauerj** [comment]
It now works like this:

```
>>> print(MacLookup().lookup("05:80:41:12:FE"))
Traceback (most recent call last):
  File "/mnt/c/Users/bauerj/git/mac_vendor_lookup/mac_vendor_lookup.py", line 104, in lookup
    return self.prefixes[mac[:6]].decode("utf8")
KeyError: b'058041'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/bauerj/git/mac_vendor_lookup/mac_vendor_lookup.py", line 122, in lookup
    return self.loop.run_until_complete(self.async_lookup.lookup(mac))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/c/Users/bauerj/git/mac_vendor_lookup/mac_vendor_lookup.py", line 106, in lookup
    raise VendorNotFoundError(mac)
mac_vendor_lookup.VendorNotFoundError: The vendor for MAC b'05804112FE' could not be found. Either it's not registered or the local list is out of date. Try MacLookup().update_vendors()
>>>
```
