### ISSUE TITLE
KeyError for MAC with unregistered prefix

### ISSUE THREAD

**Issue by MrCarney** [bauerj/mac_vendor_lookup#4]
I'm receiving a KeyError when trying to resolve `56:26:9A:C2:54:D5`
```
    return self.loop.run_until_complete(self.async_lookup.lookup(mac))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pdcarney/.local/lib/python3.5/site-packages/mac_vendor_lookup.py", line 72, in lookup
    return self.prefixes[mac[:6]].decode("utf8")
KeyError: b'56269A'
```

**Comment by bauerj** [comment]
What did you expect to get?

**Comment by MrCarney** [comment]
I guess what I'm confused about is that my program appears to be erroring out - spewing out a stack trace and then exiting. I expected maybe an empty string or an error, but not what appears to be a crash. This could _very easily_ just be me not being good at python programming. Do I need a with statement or a try-catch block?

**Comment by bauerj** [comment]
Yes, you're right. It would definitely be possible to just return `None` instead. I guess it's a matter of preference, neither would be better.

So if you want to handle the exceptions, you can write something like this:

```python
from mac_vendor_lookup import MacLookup, InvalidMacError

def lookup(mac):
    try:
        vendor = MacLookup().lookup(mac)
        print("MAC address {} is assigned to {}".format(mac, vendor))
    except KeyError:
        print("{} is not assigned to anyone".format(mac))
    except InvalidMacError:
        print("{} is not a valid MAC address".format(mac))

if __name__ == "__main__":
    while True:
        lookup(input("Please enter MAC address: "))
```

> Please enter MAC address: 56:26:9A:C2:54:D5
56:26:9A:C2:54:D5 is not assigned to anyone
Please enter MAC address: test
test is not a valid MAC address
Please enter MAC address: 00:80:41:12:FE
MAC address 00:80:41:12:FE is assigned to VEB KOMBINAT ROBOTRON

**Comment by MrCarney** [comment]
I really appreciate your help with this and I'm terribly sorry to have bothered you with a coding error. Thanks for your patience and for the great work here.

**Comment by bauerj** [comment]
No worries at all. I'm glad I could help. I know how confusing it can be to learn to use an unknown programming language or library.

I'm closing this issue for now. If you have anything else please feel free to reopen.
