### ISSUE TITLE
Synchronous methods do not work when running on non main-thread

### ISSUE THREAD

**Issue by bauerj** [bauerj/mac_vendor_lookup#5]
![grafik](https://user-images.githubusercontent.com/598790/77431657-4ae5de00-6ddd-11ea-84ff-27d3d13fc3dd.png)

**Comment by bauerj** [comment]
@procamora This should be fixed now. Could you please test the new release?

**Comment by procamora** [comment]
Yes, it works fine for me, thanks

I have seen that you use os.path to manage routes, I don't know if you know the pathlib library, but I advise you to use it, it simplifies your life managing routes and the way to use it is similar to os.path:

\>>> from pathlib import Path
\>>> Path().home()
PosixPath('/home/procamora')
\>>> Path(Path().home(), '.cache/')
PosixPath('/home/procamora/.cache')
\>>> Path('~/.cache/mac-vendors.txt').expanduser()
PosixPath('/home/procamora/.cache/mac-vendors.txt')

**Comment by bauerj** [comment]
Thanks, I'll keep that in mind!
