### ISSUE TITLE
Store list in path relative to calling script?

### ISSUE THREAD

**Issue by alepodj** [bauerj/mac_vendor_lookup#8]
Hello, 1st of all excellent app, love how quick and simple to use it is.

Quick questions/request. Is there a way to store the mac-vendors.txt in a relative path to the python script calling the `mac.update_vendors()`.

Folder Structure

```
web[folder]
  |
  |_______scripts[folder]
  |                   |_________my_script.py
  |
  |_______cache[folder]
                      |_________mac-address.py
```

my_script.py
```
mac = MacLookup()
mac.update_vendors()

address = '0000.1111.2222'
print(mac.lookup(address))
```

Thanks in advance

**Comment by alepodj** [comment]
hehehe got it figure out, im overriding the cache_path of BaseMacLookup before i execute to the path where i want the cache to exists

```
from mac_vendor_lookup import MacLookup, BaseMacLookup

BaseMacLookup.cache_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + r"\cache\mac-vendors.txt"
mac = MacLookup()
mac.update_vendors()

address = '7872.5d46.748a'
print(mac.lookup(address))
```

**Comment by bauerj** [comment]
Sorry for not responding earlier! Indeed, this looks like the right solution.

Would you mind sending in a Pull Request with a change to the README detailing what you did?

**Comment by alepodj** [comment]
Its all good :)

Sure thing ill document it and send the Pull Request soon.

**Comment by alepodj** [comment]
> 
> 
> Sorry for not responding earlier! Indeed, this looks like the right solution.
> 
> Would you mind sending in a Pull Request with a change to the README detailing what you did?

Pull request sent.
